### ISSUE TITLE
Error: `self is not defined` when importing `newTable` server side.

### ISSUE THREAD

**Issue by Khaaz** [influxdata/giraffe#475]
I have a next application where I want to render graphs on the client with giraffe. I prevented SSR to allow Giraffe to work with next.
I am using `influxdb-client-giraffe` to get data from influx in a format that works with giraffe.
However for my use case I need to connect to influx and retrieve data server side. Frontend should just get the formatted data and renders it.

When importing `newTable` from giraffe server side, I get the error: `self is not defined`. That basically prevents me to use `influxdb-client-giraffe` entirely server side since giraffe is required.

Is that an error I'm expected to encounter since giraffe shouldn't be ran server side at all?

Stack trace:
```
ReferenceError: self is not defined
    at Object.<anonymous> (/mnt/d/Projects/<user>/dashboard/node_modules/@influxdata/giraffe/dist/index.js:2:307)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1221:10)
    at Module.load (internal/modules/cjs/loader.js:1050:32)
    at Function.Module._load (internal/modules/cjs/loader.js:938:14)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.@influxdata/giraffe (/mnt/d/Projects/<user>/dashboard/.next/server/pages/api/graph.js:146:18)
    at __webpack_require__ (/mnt/d/Projects/<user>/dashboard/.next/server/pages/api/graph.js:23:31)
    at Module../src/pages/api/graph.js (/mnt/d/Projects/<user>/dashboard/.next/server/pages/api/graph.js:105:77)
```

Version: influxb-client-giraffe 1.10.0, giraffe 2.0.1
Platform: windows 10

**Comment by kristinarobinson** [comment]
Yes, this is an expected error, since Giraffe does not support server-side rendering.
